CREATE VIEW CHARGES
AS SELECT "ANO_APLICACION","MES_APLICACION","DIAS","TIM","IPM","TASA_INTERES_DEVOLUCION","IPM_VARIACION_MENSUAL" FROM APP2OBJ.MES_APLICACION;


CREATE VIEW MOVEMENTS
AS SELECT APP2OBJ.CTA_CTE_RENTA_CUOTA.CUENTA_CORRIENTE_RESUMEN_ID
FROM APP2OBJ.CTA_CTE_RENTA
INNER JOIN APP2OBJ.CTA_CTE_RENTA_CUOTA
ON APP2OBJ.CTA_CTE_RENTA_CUOTA.CTA_CTE_RENTA_ID = APP2OBJ.CTA_CTE_RENTA.CTA_CTE_RENTA_ID
AND APP2OBJ.CTA_CTE_RENTA_CUOTA.SEC_EJEC        = APP2OBJ.CTA_CTE_RENTA.SEC_EJEC
WHERE APP2OBJ.CTA_CTE_RENTA_CUOTA.CUENTA_CORRIENTE_RESUMEN_ID
in (select app2obj.movimiento_caja_detalle.cuenta_corriente_resumen_id from app2obj.movimiento_caja_detalle
where app2obj.movimiento_caja_detalle.cuenta_corriente_resumen_id = APP2OBJ.CTA_CTE_RENTA_CUOTA.CUENTA_CORRIENTE_RESUMEN_ID)
AND APP2OBJ.CTA_CTE_RENTA.ANO_APLICACION=2016;


CREATE VIEW PERSONS
AS SELECT APP2OBJ.PERSONA_MUNICIPIO.PERSONA_MUNICIPIO_ID,
  APP2OBJ.PERSONA.TIPO_DOC,
  APP2OBJ.PERSONA.NUM_DOC,
  APP2OBJ.PERSONA.APELLIDO_PATERNO,
  APP2OBJ.PERSONA.APELLIDO_MATERNO,
  APP2OBJ.PERSONA.NOMBRE,
  (APP2OBJ.PERSONA.APELLIDO_PATERNO
  || ' '
  || APP2OBJ.PERSONA.APELLIDO_MATERNO
  || ' '
  || APP2OBJ.PERSONA.NOMBRE) AS DATOS_COMPLETO,
  (APP2OBJ.TIPO_HABILITACION.DESCRIPCION
  || ' '
  || APP2OBJ.PERSONA_MUNICIPIO.NOMBRE_HABILITACION
  || ' '
  || APP2OBJ.TIPO_VIA.DESCRIPCION
  || ' '
  || APP2OBJ.PERSONA_MUNICIPIO.NOMBRE_VIA
  || ' Mz '
  || APP2OBJ.PERSONA_MUNICIPIO.MZ_URBANA
  || ' Lt '
  || APP2OBJ.PERSONA_MUNICIPIO.LOTE
  || ' Km '
  || APP2OBJ.PERSONA_MUNICIPIO.KM
  || ' Nø '
  || APP2OBJ.PERSONA_MUNICIPIO.NUMERO_DIRECCION) AS DIRECCION
FROM APP2OBJ.PERSONA_MUNICIPIO
INNER JOIN APP2OBJ.PERSONA
ON APP2OBJ.PERSONA_MUNICIPIO.TIPO_DOC = APP2OBJ.PERSONA.TIPO_DOC
AND APP2OBJ.PERSONA_MUNICIPIO.NUM_DOC = APP2OBJ.PERSONA.NUM_DOC
INNER JOIN APP2OBJ.TIPO_VIA
ON APP2OBJ.PERSONA_MUNICIPIO.TIPO_VIA = APP2OBJ.TIPO_VIA.TIPO_VIA
INNER JOIN APP2OBJ.TIPO_HABILITACION
ON APP2OBJ.PERSONA_MUNICIPIO.TIPO_HABILITACION = APP2OBJ.TIPO_HABILITACION.TIPO_HABILITACION;


CREATE VIEW TAXES
AS SELECT APP2OBJ.CTA_CTE_RENTA.CTA_CTE_RENTA_ID,
  APP2OBJ.CTA_CTE_RENTA.TRIBUTO,
  APP2OBJ.CTA_CTE_RENTA.ANO_APLICACION,
  APP2OBJ.CTA_CTE_RENTA.FECHA_GENERACION,
  APP2OBJ.CTA_CTE_RENTA.ESTADO_PROCESO,
  APP2OBJ.CTA_CTE_RENTA.INSOLUTO,
  APP2OBJ.CTA_CTE_RENTA.GENERADO,
  APP2OBJ.CTA_CTE_RENTA.PROPIETARIO_ID,
  APP2OBJ.CTA_CTE_RENTA_DJ.PREDIO_EXPEDIENTE_ID,
  APP2OBJ.PREDIO.PREDIO_ID,
  APP2OBJ.TRIBUTO.SIGLAS,
  APP2OBJ.DERECHO_EMISION_GRUPO.DERECHO_EMISION_GRUPO_ID,
  APP2OBJ.DERECHO_EMISION_GRUPO.DERECHO_EMISION_GRUPO_DESC,
  APP2OBJ.CTA_CTE_RENTA_CUOTA.CUOTA,
  APP2OBJ.CTA_CTE_RENTA_CUOTA.NUMERO_RECIBO_EMISION,
  ROUND(APP2OBJ.CTA_CTE_RENTA_CUOTA.IMPORTE_CUOTA, 2) AS IMPORTE_CUOTA,
  APP2OBJ.CTA_CTE_RENTA_CUOTA.IMPORTE_EMISION,
  APP2OBJ.CTA_CTE_RENTA_CUOTA.FECHA_VENCIMIENTO,
  APP2OBJ.CTA_CTE_RENTA_CUOTA.CUENTA_CORRIENTE_RESUMEN_ID
FROM APP2OBJ.CTA_CTE_RENTA
INNER JOIN APP2OBJ.CTA_CTE_RENTA_CUOTA
ON APP2OBJ.CTA_CTE_RENTA.CTA_CTE_RENTA_ID = APP2OBJ.CTA_CTE_RENTA_CUOTA.CTA_CTE_RENTA_ID
AND APP2OBJ.CTA_CTE_RENTA.SEC_EJEC        = APP2OBJ.CTA_CTE_RENTA_CUOTA.SEC_EJEC
INNER JOIN APP2OBJ.TRIBUTO_PERIODO
ON APP2OBJ.CTA_CTE_RENTA.SEC_EJEC        = APP2OBJ.TRIBUTO_PERIODO.SEC_EJEC
AND APP2OBJ.CTA_CTE_RENTA.TRIBUTO        = APP2OBJ.TRIBUTO_PERIODO.TRIBUTO
AND APP2OBJ.CTA_CTE_RENTA.ANO_APLICACION = APP2OBJ.TRIBUTO_PERIODO.ANO_APLICACION
INNER JOIN APP2OBJ.TRIBUTO
ON APP2OBJ.TRIBUTO_PERIODO.SEC_EJEC = APP2OBJ.TRIBUTO.SEC_EJEC
AND APP2OBJ.TRIBUTO_PERIODO.TRIBUTO = APP2OBJ.TRIBUTO.TRIBUTO
INNER JOIN APP2OBJ.DERECHO_EMISION_GRUPO
ON APP2OBJ.DERECHO_EMISION_GRUPO.SEC_EJEC = APP2OBJ.TRIBUTO.SEC_EJEC
AND APP2OBJ.DERECHO_EMISION_GRUPO.TRIBUTO = APP2OBJ.TRIBUTO.TRIBUTO
INNER JOIN APP2OBJ.CTA_CTE_RENTA_DJ
ON APP2OBJ.CTA_CTE_RENTA.CTA_CTE_RENTA_ID = APP2OBJ.CTA_CTE_RENTA_DJ.CTA_CTE_RENTA_ID
AND APP2OBJ.CTA_CTE_RENTA.SEC_EJEC        = APP2OBJ.CTA_CTE_RENTA_DJ.SEC_EJEC
INNER JOIN APP2OBJ.PREDIO_EXPEDIENTE
ON APP2OBJ.CTA_CTE_RENTA_DJ.PREDIO_EXPEDIENTE_ID = APP2OBJ.PREDIO_EXPEDIENTE.PREDIO_EXPEDIENTE_ID
INNER JOIN APP2OBJ.PREDIO
ON APP2OBJ.PREDIO_EXPEDIENTE.SEC_EJEC   = APP2OBJ.PREDIO.SEC_EJEC
AND APP2OBJ.PREDIO_EXPEDIENTE.PREDIO_ID = APP2OBJ.PREDIO.PREDIO_ID
WHERE APP2OBJ.CTA_CTE_RENTA.ANO_APLICACION=2016;
